title: Professor Svetlana "Lana" Yarosh - University of Minnesota
page-top-title: Lana Yarosh
top-section-bg-text: Computer Science
home-subtitle: Professor Svetalan "Lana" Yarosh - University of Minnesota
copyright-text: ''
